### ISSUE TITLE
No support for xUnit output

### ISSUE THREAD

**Issue by sobolewska** [reportunit/reportunit#18]
Although documentations states that it supports xunit, it dos NOT read xunit result xml file. example xunit (produced by python nose --with-xunit) looks like this:
```xml
<testsuite name="nosetests" tests="3" errors="0" failures="0" skip="0">
<testcase classname="tests.folder_name.file_name_a.ClassA" name="test_A_1" time="48.462"/>
<testcase classname="tests.folder_name.file_name_b.ClassB" name="test_B_1" time="48.462"/>
<testcase classname="tests.folder_name.file_name_b.ClassB" name="test_B_2" time="48.462"/>
</testsuite>
```

**Comment by anshooarora** [comment]
Can you share a sample results file?  I will check.

**Comment by sobolewska** [comment]
```
<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="nosetests" tests="3" errors="0" failures="1" skip="1">
    <testcase classname="tests.SimpleTest" name="test_fail" time="0.000">
        <failure type="exceptions.AssertionError" message="11 != 10">
            <![CDATA[Traceback (most recent call last):
File "/opt/python-2.6.1/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/case.py", line 340, in run
testMethod()
File "/home/damien/tests.py", line 16, in test_fail
self.assertEqual(11, 7 + 3)
File "/opt/python-2.6.1/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/case.py", line 521, in assertEqual
assertion_func(first, second, msg=msg)
File "/opt/python-2.6.1/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/case.py", line 514, in _baseAssertEqual
raise self.failureException(msg)
AssertionError: 11 != 10
]]>
        </failure>
    </testcase>
    <testcase classname="tests.SimpleTest" name="test_pass" time="0.000"></testcase>
    <testcase classname="tests.SimpleTest" name="test_skipped" time="0.000">
        <skipped type="nose.plugins.skip.SkipTest" message="demonstrating skipping">
            <![CDATA[SkipTest: demonstrating skipping
]]>
        </skipped>
    </testcase>
</testsuite>
```

**Comment by anshooarora** [comment]
Thanks.  This will be fixed in the upcoming version.  We are currently working on improving all parsers and please feel free to send in a pull request.

Upcoming samples:  http://relevantcodes.com/Tools/ReportUnit/1.5/NUnit-3b2.html

**Comment by joshuaduffy** [comment]
FYI- [xUnit for Python](http://nose.readthedocs.org/en/latest/plugins/xunit.html) and [xUnit 2.X for .NET](https://xunit.github.io/docs/format-xml-v2.html) have differing formats.

**Comment by anshooarora** [comment]
Joshua - do you have a sample of xUnit that I can use to add support?  All parsers are ready except xUnit so would love to see a few samples for testing.

**Comment by joshuaduffy** [comment]
For xUnit.NET?

I can't provide any reports that I currently generate (work related...) but I'm happy to test it out for you, are you using the Revert-15-Master branch for the latest release?

**Comment by joshuaduffy** [comment]
What is the difference between this and the extentreports library?

**Comment by anshooarora** [comment]
Latest:  https://github.com/reportunit/reportunit/tree/1.50.0

ExtentReports is a logger, ReportUnit only converts raw to HTML.

**Comment by joshuaduffy** [comment]
Great thank you, I have a very long xml output (over 20k lines) that I will feed through ReportUnit tonight, I'll let you know how I get on!

**Comment by joshuaduffy** [comment]
The current report format assumes one assembly per xml file, xUnit report formats contain multiple assemblies in one report.

**Comment by anshooarora** [comment]
Sandra was maintaining the xUnit parser, you can view her commit for v2 here:  https://github.com/reportunit/reportunit/blob/8b72f262bcff1be8a2dfa550f09b07ac51c150df/ReportUnit/Parser/XUnitV2.cs

**Comment by eliteofindia** [comment]
Hi Anshoo,
I was using ReportUnit 1.5 Beta and found an issue-
Like once we have a fail case and we click the red mark to know the details about cause a new div opened with details but if you click on the content of that div the entire page is wrapped with a transparent div and you will not be able to perform any action on the report  page.

**Comment by darkainsoul** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="C:\Automation\UI.Automation\test\TestCases\bin\Debug\net46\win7-x64\TestCases.DLL" environment="64-bit .NET 4.0.30319.42000 [collection-per-class, parallel (4 threads)]" test-framework="xUnit.net 2.1.0.3179" run-date="2016-07-05" run-time="10:10:39" config-file="C:\Automation\UI.Automation\test\TestCases\bin\Debug\net46\win7-x64\TestCases.dll.config" total="37" passed="24" failed="13" skipped="0" time="2021.818" errors="0">
    <errors />
    <collection total="7" passed="7" failed="0" skipped="0" name="Download Test Cases" time="1534.679">
      <test name="TestCases.Download_TestCases.DownloadsHardFailDownloads" type="TestCases.Download_TestCases" method="DownloadsHardFailDownloads" time="645.3168903" result="Pass" />
      <test name="TestCases.Download_TestCases.DownloadsUserNavigatesToDownloadsLandingPage" type="TestCases.Download_TestCases" method="DownloadsUserNavigatesToDownloadsLandingPage" time="163.6201271" result="Pass" />
      <test name="TestCases.Download_TestCases.DownloadsSearchSoftwareDownloadsPageGeneralSearch" type="TestCases.Download_TestCases" method="DownloadsSearchSoftwareDownloadsPageGeneralSearch" time="97.7931232" result="Pass" />
      <test name="TestCases.Download_TestCases.DownloadsSoftFail" type="TestCases.Download_TestCases" method="DownloadsSoftFail" time="277.3336082" result="Pass" />
      <test name="TestCases.Download_TestCases.DownloadsMyDownloadsPage" type="TestCases.Download_TestCases" method="DownloadsMyDownloadsPage" time="116.6606583" result="Pass" />
      <test name="TestCases.Download_TestCases.DownloadsUserDownloadsMultipleBinariesFromMyDownloadsUsingSelectAll" type="TestCases.Download_TestCases" method="DownloadsUserDownloadsMultipleBinariesFromMyDownloadsUsingSelectAll" time="122.4366562" result="Pass" />
      <test name="TestCases.Download_TestCases.DownloadsUserAddsProductToMyDownloadsFolder" type="TestCases.Download_TestCases" method="DownloadsUserAddsProductToMyDownloadsFolder" time="111.5183067" result="Pass" />
    </collection>
    <collection total="9" passed="9" failed="0" skipped="0" name="KnowledgeBase Test Cases" time="1882.450">
      <test name="TestCases.KnowledgeBase_TestCases.KBUserFiltersSearchResultsUsingTopicFacet" type="TestCases.KnowledgeBase_TestCases" method="KBUserFiltersSearchResultsUsingTopicFacet" time="132.4302362" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.LoginSNWLInterstitialPageKB" type="TestCases.KnowledgeBase_TestCases" method="LoginSNWLInterstitialPageKB" time="249.3380213" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.KBSearchLandingCannotSeeInternalArticles" type="TestCases.KnowledgeBase_TestCases" method="KBSearchLandingCannotSeeInternalArticles" time="69.0506862" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.KBUserFiltersSearchResultsUsingProductFacet" type="TestCases.KnowledgeBase_TestCases" method="KBUserFiltersSearchResultsUsingProductFacet" time="137.8370276" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.KBUserLoggedInNavigatesBaseDetailsAndViews" type="TestCases.KnowledgeBase_TestCases" method="KBUserLoggedInNavigatesBaseDetailsAndViews" time="162.0359686" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.KBInternalUserViewsDifferentStatusOfArticles" type="TestCases.KnowledgeBase_TestCases" method="KBInternalUserViewsDifferentStatusOfArticles" time="75.7439488" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.KBSearchProductFilterResults" type="TestCases.KnowledgeBase_TestCases" method="KBSearchProductFilterResults" time="254.5035857" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.KBUserFiltersSearchResultsUsingVersionFacet" type="TestCases.KnowledgeBase_TestCases" method="KBUserFiltersSearchResultsUsingVersionFacet" time="132.0192981" result="Pass" />
      <test name="TestCases.KnowledgeBase_TestCases.KBPartnerUserloggedNavigatesKnowledge" type="TestCases.KnowledgeBase_TestCases" method="KBPartnerUserloggedNavigatesKnowledge" time="669.4912304" result="Pass" />
    </collection>
    <collection total="9" passed="2" failed="7" skipped="0" name="ServiceRequest Test Cases" time="1776.635">
      <test name="TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSoftFail" type="TestCases.ServiceRequest_TestCases" method="CreateServiceRequestForExternalUserSoftFail" time="285.894158" result="Fail">
        <failure exception-type="OpenQA.Selenium.WebDriverException">
          <message><![CDATA[OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:24277/session/a3f3814e78603b2f43f4e7e01c3ce619/element/0.8822862616711602-5/elements timed out after 60 seconds.\r\n---- System.Net.WebException : The operation has timed out]]></message>
          <stack-trace><![CDATA[   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElements(String mechanism, String value)
   at OpenQA.Selenium.Support.UI.SelectElement.SelectByText(String text)
   at Framework.Controls.Dropdown.Select(String option, Boolean remote) in C:\Automation\UI.Automation\test\Framework\Controls\Dropdown.cs:line 75
   at Framework.Pages.ServiceRequest.CreateSrSoftFail() in C:\Automation\UI.Automation\test\Framework\Pages\ServiceRequest.cs:line 160
   at TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSoftFail() in C:\Automation\UI.Automation\test\TestCases\ServiceRequest_TestCases.cs:line 73
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSuccessfully" type="TestCases.ServiceRequest_TestCases" method="CreateServiceRequestForExternalUserSuccessfully" time="288.2743546" result="Fail">
        <failure exception-type="OpenQA.Selenium.WebDriverException">
          <message><![CDATA[OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:1895/session/95d4ecc9a783671579bd45304630f513/element/0.6108004278873345-5/elements timed out after 60 seconds.\r\n---- System.Net.WebException : The operation has timed out]]></message>
          <stack-trace><![CDATA[   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElements(String mechanism, String value)
   at OpenQA.Selenium.Support.UI.SelectElement.SelectByText(String text)
   at Framework.Controls.Dropdown.Select(String option, Boolean remote) in C:\Automation\UI.Automation\test\Framework\Controls\Dropdown.cs:line 75
   at Framework.Pages.ServiceRequest.CreateSrExternalSuccessfully() in C:\Automation\UI.Automation\test\Framework\Pages\ServiceRequest.cs:line 132
   at TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSuccessfully() in C:\Automation\UI.Automation\test\TestCases\ServiceRequest_TestCases.cs:line 47
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.ServiceRequest_TestCases.PartnerUserCreateServiceRequestForPartnerAccount" type="TestCases.ServiceRequest_TestCases" method="PartnerUserCreateServiceRequestForPartnerAccount" time="284.5461889" result="Fail">
        <failure exception-type="OpenQA.Selenium.WebDriverException">
          <message><![CDATA[OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:62461/session/caf9f41d2831283ca010b8ce5ff5f0b3/element timed out after 60 seconds.\r\n---- System.Net.WebException : The operation has timed out]]></message>
          <stack-trace><![CDATA[   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.FindElement(String mechanism, String value)
   at Framework.Controls.Element.FindByXPathOrId(IWebElement& elem) in C:\Automation\UI.Automation\test\Framework\Controls\Element.cs:line 92
   at Framework.Controls.Dropdown.GetElement() in C:\Automation\UI.Automation\test\Framework\Controls\Dropdown.cs:line 165
   at Framework.Controls.Dropdown.SelectDivList(String option) in C:\Automation\UI.Automation\test\Framework\Controls\Dropdown.cs:line 96
   at Framework.Pages.ServiceRequest.CreateForPartnerSrSuccessfully() in C:\Automation\UI.Automation\test\Framework\Pages\ServiceRequest.cs:line 89
   at TestCases.ServiceRequest_TestCases.PartnerUserCreateServiceRequestForPartnerAccount() in C:\Automation\UI.Automation\test\TestCases\ServiceRequest_TestCases.cs:line 158
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.ServiceRequest_TestCases.PartnerUserCreateServiceRequestForNonPartnerAccount" type="TestCases.ServiceRequest_TestCases" method="PartnerUserCreateServiceRequestForNonPartnerAccount" time="108.9365035" result="Fail">
        <failure exception-type="OpenQA.Selenium.WebDriverException">
          <message><![CDATA[OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:3410/session/ae7e34b4008cad1ccf056794271c568c/element/0.8181398844347996-2/elements timed out after 60 seconds.\r\n---- System.Net.WebException : The operation has timed out]]></message>
          <stack-trace><![CDATA[   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElements(String mechanism, String value)
   at OpenQA.Selenium.Support.UI.SelectElement.SelectByText(String text)
   at Framework.Controls.Dropdown.Select(String option, Boolean remote) in C:\Automation\UI.Automation\test\Framework\Controls\Dropdown.cs:line 75
   at Framework.Pages.ServiceRequest.CreateSincePartnerSrSuccessfully() in C:\Automation\UI.Automation\test\Framework\Pages\ServiceRequest.cs:line 106
   at TestCases.ServiceRequest_TestCases.PartnerUserCreateServiceRequestForNonPartnerAccount() in C:\Automation\UI.Automation\test\TestCases\ServiceRequest_TestCases.cs:line 204
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSuccessfullyWithAttachmentAndNoteWhileCreateSR" type="TestCases.ServiceRequest_TestCases" method="CreateServiceRequestForExternalUserSuccessfullyWithAttachmentAndNoteWhileCreateSR" time="279.6301726" result="Fail">
        <failure exception-type="OpenQA.Selenium.WebDriverException">
          <message><![CDATA[OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:3744/session/d10497239e638f52ba141746aff33493/element/0.8937228074397174-5/elements timed out after 60 seconds.\r\n---- System.Net.WebException : The operation has timed out]]></message>
          <stack-trace><![CDATA[   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElements(String mechanism, String value)
   at OpenQA.Selenium.Support.UI.SelectElement.SelectByText(String text)
   at Framework.Controls.Dropdown.Select(String option, Boolean remote) in C:\Automation\UI.Automation\test\Framework\Controls\Dropdown.cs:line 75
   at Framework.Pages.ServiceRequest.CreateSrExternalSuccessfully() in C:\Automation\UI.Automation\test\Framework\Pages\ServiceRequest.cs:line 132
   at TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSuccessfullyWithAttachmentAndNoteWhileCreateSR() in C:\Automation\UI.Automation\test\TestCases\ServiceRequest_TestCases.cs:line 86
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSuccessfullyWithAttachmentAndNoteAfterCreateSR" type="TestCases.ServiceRequest_TestCases" method="CreateServiceRequestForExternalUserSuccessfullyWithAttachmentAndNoteAfterCreateSR" time="283.0762698" result="Fail">
        <failure exception-type="OpenQA.Selenium.WebDriverException">
          <message><![CDATA[OpenQA.Selenium.WebDriverException : The HTTP request to the remote WebDriver server for URL http://localhost:54301/session/d0294003eb126e1545c1b21388e18c20/element/0.9850678972992903-5/elements timed out after 60 seconds.\r\n---- System.Net.WebException : The operation has timed out]]></message>
          <stack-trace><![CDATA[   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)
   at OpenQA.Selenium.Remote.HttpCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.DriverServiceCommandExecutor.Execute(Command commandToExecute)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebElement.FindElements(String mechanism, String value)
   at OpenQA.Selenium.Support.UI.SelectElement.SelectByText(String text)
   at Framework.Controls.Dropdown.Select(String option, Boolean remote) in C:\Automation\UI.Automation\test\Framework\Controls\Dropdown.cs:line 75
   at Framework.Pages.ServiceRequest.CreateSrExternalSuccessfully() in C:\Automation\UI.Automation\test\Framework\Pages\ServiceRequest.cs:line 132
   at TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserSuccessfullyWithAttachmentAndNoteAfterCreateSR() in C:\Automation\UI.Automation\test\TestCases\ServiceRequest_TestCases.cs:line 102
----- Inner Stack Trace -----
   at System.Net.HttpWebRequest.GetResponse()
   at OpenQA.Selenium.Remote.HttpCommandExecutor.CreateResponse(WebRequest request)]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.ServiceRequest_TestCases.CreateCustomerServiceRequestForSNWLUserSuccessfully" type="TestCases.ServiceRequest_TestCases" method="CreateCustomerServiceRequestForSNWLUserSuccessfully" time="136.958192" result="Pass" />
      <test name="TestCases.ServiceRequest_TestCases.CreateServiceRequestForDSGUser" type="TestCases.ServiceRequest_TestCases" method="CreateServiceRequestForDSGUser" time="62.2747661" result="Pass" />
      <test name="TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserHardFail" type="TestCases.ServiceRequest_TestCases" method="CreateServiceRequestForExternalUserHardFail" time="47.0446503" result="Fail">
        <failure exception-type="Xunit.Sdk.ContainsException">
          <message><![CDATA[Assert.Contains() Failure\r\nNot found: Expired Maintenance\r\nIn value:  Hard Fail Trial]]></message>
          <stack-trace><![CDATA[   at Framework.Pages.ServiceRequest.CreateSrHardFail() in C:\Automation\UI.Automation\test\Framework\Pages\ServiceRequest.cs:line 150
   at TestCases.ServiceRequest_TestCases.CreateServiceRequestForExternalUserHardFail() in C:\Automation\UI.Automation\test\TestCases\ServiceRequest_TestCases.cs:line 61]]></stack-trace>
        </failure>
      </test>
    </collection>
    <collection total="6" passed="6" failed="0" skipped="0" name="Login Test Cases" time="343.705">
      <test name="TestCases.LogIn_TestCases.SignInSPHomePage_InValidUser" type="TestCases.LogIn_TestCases" method="SignInSPHomePage_InValidUser" time="47.8433978" result="Pass" />
      <test name="TestCases.LogIn_TestCases.SignInSPHomePage_DMAUser" type="TestCases.LogIn_TestCases" method="SignInSPHomePage_DMAUser" time="39.5970641" result="Pass" />
      <test name="TestCases.LogIn_TestCases.SignInSPHomePage_IncorrectEmail" type="TestCases.LogIn_TestCases" method="SignInSPHomePage_IncorrectEmail" time="43.8699234" result="Pass" />
      <test name="TestCases.LogIn_TestCases.SignInSPHomePage_SNWLUser" type="TestCases.LogIn_TestCases" method="SignInSPHomePage_SNWLUser" time="134.9851617" result="Pass" />
      <test name="TestCases.LogIn_TestCases.SignInSPHomePage_TrialUser" type="TestCases.LogIn_TestCases" method="SignInSPHomePage_TrialUser" time="39.4518639" result="Pass" />
      <test name="TestCases.LogIn_TestCases.SignInSPHomePage_QuestInternalUser" type="TestCases.LogIn_TestCases" method="SignInSPHomePage_QuestInternalUser" time="37.9578948" result="Pass" />
    </collection>
    <collection total="6" passed="0" failed="6" skipped="0" name="Registration Test Cases" time="138.971">
      <test name="TestCases.Registration_TestCases.NewCustomerDontKnowYourAccountInformation" type="TestCases.Registration_TestCases" method="NewCustomerDontKnowYourAccountInformation" time="36.7333904" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at TestCases.Registration_TestCases.GetTemporaryPassword(CreateEmailAddress validMail) in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 168
   at TestCases.Registration_TestCases.NewCustomerDontKnowYourAccountInformation() in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 50]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.Registration_TestCases.UserRegistersWithAccountIDNavigatesToMyLicensePage" type="TestCases.Registration_TestCases" method="UserRegistersWithAccountIDNavigatesToMyLicensePage" time="18.4055022" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at TestCases.Registration_TestCases.GetTemporaryPassword(CreateEmailAddress validMail) in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 168
   at TestCases.Registration_TestCases.UserRegistersWithAccountIDNavigatesToMyLicensePage() in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 83]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.Registration_TestCases.UserRegistersWithAccountID" type="TestCases.Registration_TestCases" method="UserRegistersWithAccountID" time="19.4600493" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at TestCases.Registration_TestCases.GetTemporaryPassword(CreateEmailAddress validMail) in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 168
   at TestCases.Registration_TestCases.UserRegistersWithAccountID() in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 64]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.Registration_TestCases.UserRegistersOnSupportPortalWithATrailLicenseProduct" type="TestCases.Registration_TestCases" method="UserRegistersOnSupportPortalWithATrailLicenseProduct" time="21.4809254" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at TestCases.Registration_TestCases.GetTemporaryPassword(CreateEmailAddress validMail) in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 168
   at TestCases.Registration_TestCases.UserRegistersOnSupportPortalWithATrailLicenseProduct() in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 127]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.Registration_TestCases.UserRegistersOnSupportPortalWithATrailLicenseProductNavigatesToMyProduct" type="TestCases.Registration_TestCases" method="UserRegistersOnSupportPortalWithATrailLicenseProductNavigatesToMyProduct" time="25.8577928" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at TestCases.Registration_TestCases.GetTemporaryPassword(CreateEmailAddress validMail) in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 168
   at TestCases.Registration_TestCases.UserRegistersOnSupportPortalWithATrailLicenseProductNavigatesToMyProduct() in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 147]]></stack-trace>
        </failure>
      </test>
      <test name="TestCases.Registration_TestCases.UserRegistersUsingTheLicenseNumberThatIsRegisteredBefore" type="TestCases.Registration_TestCases" method="UserRegistersUsingTheLicenseNumberThatIsRegisteredBefore" time="17.0335639" result="Fail">
        <failure exception-type="System.NullReferenceException">
          <message><![CDATA[System.NullReferenceException : Object reference not set to an instance of an object.]]></message>
          <stack-trace><![CDATA[   at TestCases.Registration_TestCases.GetTemporaryPassword(CreateEmailAddress validMail) in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 168
   at TestCases.Registration_TestCases.UserRegistersUsingTheLicenseNumberThatIsRegisteredBefore() in C:\Automation\UI.Automation\test\TestCases\Registration_TestCases.cs:line 107]]></stack-trace>
        </failure>
      </test>
    </collection>
  </assembly>
</assemblies>`
