### ISSUE TITLE
Bug: Crashes if NUnit 3 xml contains no test results

### ISSUE THREAD

**Issue by espenalb** [reportunit/reportunit#30]
This should not crash - happens in our test suite when we are only running SmokeTests...
```
12:03:40   Unhandled Exception: System.InvalidOperationException: Sequence contains no elements
12:03:40      at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
12:03:40      at ReportUnit.Parser.NUnit.CreateRunInfo(XDocument doc, Report report)
12:03:40      at ReportUnit.Parser.NUnit.Parse(String resultsFile)
12:03:40      at ReportUnit.ReportUnitService.CreateFolderReport(String inputDirectory, String outputDirectory)
12:03:40      at ReportUnit.Program.Main(String[] args)
```

**Comment by espenalb** [comment]
This is the test report:
```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<test-run id="2" testcasecount="0" result="Failed" label="Invalid" total="0" passed="0" failed="0" inconclusive="0" skipped="0" asserts="0" engine-version="3.0.5813.39036" clr-version="4.0.30319.42000" start-time="2015-12-15 10:54:30Z" end-time="2015-12-15 10:54:30Z" duration="0.006484">
  <command-line><![CDATA[J:\Jenkins\jobs\GsWindows-feature\workspace\\packages\NUnit.Console.3.0.1\tools\\nunit3-console.exe  J:\Jenkins\jobs\GsWindows-feature\workspace\GsViewer.Tests\\bin\Debug\\GsViewer2.Tests.dll --result=J:\Jenkins\jobs\GsWindows-feature\workspace\artifacts\TestResults\IntegrationTests\GsViewer2.Tests.xml;format=nunit3 --where="cat=~MergeTests AND cat!~TestDurationLong" --result=J:\Jenkins\jobs\GsWindows-feature\workspace\\TestResults\\NUnit-GsViewer2.Tests.xml;format=nunit2 --x86]]></command-line>
  <filter>
    <and>
      <cat re="1">MergeTests</cat>
      <not>
        <cat re="1">TestDurationLong</cat>
      </not>
    </and>
  </filter>
  <test-suite type="Assembly" id="0-1" name="GsViewer2.Tests.dll" fullname="J:\Jenkins\jobs\GsWindows-feature\workspace\GsViewer.Tests\bin\Debug\GsViewer2.Tests.dll" testcasecount="0" runstate="NotRunnable" result="Failed" label="Invalid">
    <properties>
      <property name="_SKIPREASON" value="No suitable tests found in 'J:\Jenkins\jobs\GsWindows-feature\workspace\GsViewer.Tests\bin\Debug\GsViewer2.Tests.dll'.&#xA;Either assembly contains no tests or proper test driver has not been found." />
    </properties>
    <reason>
      <message>No suitable tests found in 'J:\Jenkins\jobs\GsWindows-feature\workspace\GsViewer.Tests\bin\Debug\GsViewer2.Tests.dll'.
Either assembly contains no tests or proper test driver has not been found.</message>
    </reason>
  </test-suite>
</test-run>
```

**Comment by anshooarora** [comment]
Can you test with the latest 661fa1b003a124789e037ef464672cd9849b4ab3 to see if it works for you?

**Comment by espenalb** [comment]
Works perfectly. Excellent!
One minor suggestion: Maybe show the "reason" when there are no tests found?

**Comment by anshooarora** [comment]
Adds message: https://github.com/reportunit/reportunit/commit/ebd93015bbaaef91c8b7f05f4daa705b19181109.
