### ISSUE TITLE
ReportUnit crashes when given a path with double \\

### ISSUE THREAD

**Issue by espenalb** [reportunit/reportunit#34]
This crashes:
```
ReportUnit.exe C:\Documents\GasSecure\GitHub\test\windows\.build\\..\\artifacts\TestResults\IntegrationTests\\
```
But this is OK:
```
C:\Documents\GasSecure\GitHub\test\windows>C:\Documents\GasSecure\GitHub\test\windows\\.build\ReportUnit-1.5-alpha\R
```

Crash is a nullreference
``` 
--
ReportUnit v1.5. Report generator for the test-runner family.
http://reportunit.relevantcodes.com/
Copyright (c) 2015 Anshoo Arora (Relevant Codes)
Developers:  Anshoo Arora, Sandra Greenhalgh
--

[2016.01.06 11.29.48][Info] The file C:\Documents\GasSecure\GitHub\test\windows\.build\\..\\artifacts\TestResults\IntegrationTests\\GsTerm.html contains Unknown test results
[2016.01.06 11.29.48][Info] The file C:\Documents\GasSecure\GitHub\test\windows\.build\\..\\artifacts\TestResults\IntegrationTests\\GsTerm.Tests.xml contains Unknown test results

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at ReportUnit.ReportUnitService.CreateReport(String input, String outputDirectory)
   at ReportUnit.Program.Main(String[] args)
```
Simple workaround of course - don't pass in stupid paths, but can probably be fixed by wrapping path in ```System.IO.Path.GetFullPath()``` - and even adding a little check that it exists...

**Comment by anshooarora** [comment]
Hey Espen - Thanks for reporting this.  Can you send in a pull request for this?  I will merge.

**Comment by espenalb** [comment]
Seems to be fixed now...
