### ISSUE TITLE
Nunit 3.4.1 is not supporting Appium Page Objects based on Selenium Page objects (Nunit probably cannot get test assemblies)

### ISSUE THREAD

**Issue by szczechu** [reportunit/reportunit#86]
.Net solution
Nuget Packages installed:
- Appium WebDriver 2.0.1.1
- Selenium WebDriver v2.53.1 with dependencies
- Nunit 3.4.1 with dependencies
- Visual Studio 2012 Update 5

Problems:
On Jenkins and Locally (Resharper runs Nunit3 Appium tests)

Error : MobileTests.ApplicationTests.ApplicationTests.FlowTest
System.IO.FileNotFoundException : Could not load file or assembly 'file:///C:\Program Files (x86)\Jenkins\workspace\WebDriver.Support.dll' or one of its dependencies. The system cannot find the file specified.
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadFrom(String assemblyFile, Evidence securityEvidence, Byte[] hashValue, AssemblyHashAlgorithm hashAlgorithm, Boolean forIntrospection, Boolean suppressSecurityChecks, StackCrawlMark& stackMark)
   at System.Reflection.Assembly.LoadFrom(String assemblyFile)
   at OpenQA.Selenium.Appium.PageObjects.ByFactory.From(FindsByAttribute attribute)
   at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateDefaultLocatorList(MemberInfo member)
   at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateBys(ISearchContext context, MemberInfo member)
   at OpenQA.Selenium.Appium.PageObjects.AppiumPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
   at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)
   at Apriso.Mobile.Framework.Pages.MobileAppPages.GetMobileAppPage[TPage]() in c:\Program Files (x86)\Jenkins\workspace@2\src\Apriso.Mobile.Framework\Pages\MobileAppPages.cs:line 49
   at MobileTests.ApplicationTests.ApplicationTests.SetupTest() in c:\Program Files (x86)\Jenkins\workspace@2\tests\MobileTests\ApplicationTests\ApplicationTests.cs:line 33
 
Nunit does not coppy required WebDriver.Support.dll to wokspace.
 
If I provide WebDriver.Support.dll manually, then:
MobileTests.ApplicationTests.ApplicationTests.FlexParts
System.NullReferenceException : Object reference not set to an instance of an object.
   at OpenQA.Selenium.Appium.PageObjects.ByFactory.From(FindsByAttribute attribute)
   at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateDefaultLocatorList(MemberInfo member)
   at OpenQA.Selenium.Appium.PageObjects.ByFactory.CreateBys(ISearchContext context, MemberInfo member)
   at OpenQA.Selenium.Appium.PageObjects.AppiumPageObjectMemberDecorator.Decorate(MemberInfo member, IElementLocator locator)
   at OpenQA.Selenium.Support.PageObjects.PageFactory.InitElements(Object page, IElementLocator locator, IPageObjectMemberDecorator decorator)
   at Apriso.Mobile.Framework.Pages.MobileAppPages.GetMobileAppPage[TPage]() in c:\Program Files (x86)\Jenkins\workspace@2\src\Apriso.Mobile.Framework\Pages\MobileAppPages.cs:line 48
   at MobileTests.ApplicationTests.ApplicationTests.SetupTest() in c:\Program Files (x86)\Jenkins\workspace@2\tests\MobileTests\ApplicationTests\ApplicationTests.cs:line 33
   
   
Pages are created in function:
        public static TPage GetMobileAppPage<TPage>() where TPage : new()
        {
            var page = new TPage();
            PageFactory.InitElements(Android.Driver, page, new AppiumPageObjectMemberDecorator());
            return page;
        }
		
It appears that Nunit 3.4.1 is not supporting AppiumPageObjectMemberDecorator().

Under Nunit 2.6.4 everything is working.

**Comment by szczechu** [comment]
Update:
Tests executed locally by resharper or from Windows Batch command:
`.\packages\NUnit.Runners.3.4.1\tools\nunit3-console.exe --labels all ".\tests\MobileTests\bin\Release\MobileTests.dll" --where "cat == Android" --result="selenium-testresult.xml";format=nunit2 exit %%ERRORLEVEL%% `
Are throwing above errors.

When test will be runned from test DLL directory, everything is working fine:
`cd tests\MobileTests\bin\Release
..\..\..\..\packages\NUnit.Runners.3.4.1\tools\nunit3-console.exe --labels all ".\MobileTests.dll" --where "cat == Android" --result="selenium-testresult.xml";format=nunit2 exit %%ERRORLEVEL%%`
